
on: push
    
name: Build

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install in poetry env
        run: poetry install 

      - name: Run poetry shell
        run: poetry build

      - name: Run loogck command
        run: loogck
